CREATE SCHEMA IF NOT EXISTS users;

CREATE SCHEMA IF NOT EXISTS search;

CREATE SCHEMA IF NOT EXISTS vehicle;

CREATE SCHEMA IF NOT EXISTS rental;

CREATE SCHEMA IF NOT EXISTS chat;

CREATE SCHEMA IF NOT EXISTS location;

CREATE SCHEMA IF NOT EXISTS agent;

-- GRANT USAGE ON SCHEMA users TO userservice
