//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.20 at 10:47:34 PM CEST 
//


package vehicle.model;

import vehicle.soap.WSEndpoint;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fuelArray", propOrder = {
        "item"
})
public class FuelArray {
    @XmlElement
    @XmlSchemaType(name = "fuel", namespace = WSEndpoint.NAMESPACE_URI)
    private List<Fuel> item;


    public List<Fuel> getItem() {
        if (item == null) {
            item = new ArrayList<Fuel>();
        }
        return this.item;
    }

}
